install:
  - choco install gitversion.portable -pre -y

nuget:
  disable_publish_on_pr: true

assembly_info:
  patch: false

before_build:
  - ps: gitversion /l console /output buildserver

build_script:
  - cmd: build.cmd

after_build:
  - cmd: appveyor PushArtifact "Build\NugetPacker.%GitVersion_NuGetVersion%.nupkg"
